# Generated by Django 2.2 on 2021-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210316_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='continent',
            field=models.CharField(choices=[('africa', 'Africa'), ('asia', 'Asia'), ('europe', 'Europe'), ('north america', 'North America'), ('south america', 'South America'), ('antarctica', 'Antarctica')], default='africa', max_length=250),
        ),
    ]
