# Generated by Django 2.2 on 2021-03-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210316_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='surname',
        ),
    ]
