# Generated by Django 2.2 on 2021-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210316_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='continent',
            field=models.CharField(choices=[('africa', 'Africa'), ('asia', 'Asia'), ('europe', 'Europe'), ('north america', 'North America'), ('south america', 'South America'), ('antarctica', 'Antarctica')], max_length=250),
        ),
    ]
