# Generated by Django 2.2 on 2021-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('celebrity', 'Celebrities'), ('computers', 'Computers'), ('educational', 'Educational'), ('travel', 'Travel'), ('kids', 'Kids'), ('gaming', 'Gaming')], default='general', max_length=100),
        ),
    ]
