# Generated by Django 2.2 on 2021-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210319_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ext_link1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='ext_link2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='ext_link3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='ext_link4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='ext_link5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='l1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='l2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='l3',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='l4',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='l5',
            field=models.CharField(default='', max_length=150),
        ),
    ]
